### ISSUE TITLE
You attempted to access the Value property for a failed result. A failed result has no Value

### ISSUE THREAD

**Issue by MohamedRDwedar** [vkhorikov/CSharpFunctionalExtensions#208]
I have the following issue 
any method that rerun an error i always got the below error message instead of the original error

"You attempted to access the Value property for a failed result. A failed result has no Value"

here is an example of the code usage 

try
            {
                   var value = await _dataContext.TestItems.Where(c => c.Id == 1).ToListAsync();
                    return Result.Success(value);
            }
            catch (Exception exception)
            {
                return Result.Failure<List<TestItem>>(exception.Message);
            }

what is exactly the issue or i am using the lib wrongly ..

**Comment by MohamedRDwedar** [comment]
even very simple api return have the same error 
 [HttpGet("{dom}/{sDom}")]
        public IActionResult GetPreferdLabelsBySDom(string dom, string sDom)
        {
            return Ok(Result.Success(10));
        }
CSharpFunctionalExtensions.ResultSuccessException: You attempted to access the Error property for a successful result. A successful result has no Error.
   at CSharpFunctionalExtensions.Internal.ResultCommonLogic`1.get_Error()
   at get_Error(Object )
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnWrite(WriteStackFrame& current, Utf8JsonWriter writer)
   at System.Text.Json.JsonPropertyInfo.Write(WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, br
Host: localhost:32768
User-Agent: PostmanRuntime/7.26.1
Postman-Token: 69da6259-9c7d-49b5-a28d-c1c938142f51

**Comment by leblancdavid** [comment]
We were getting that error too. I don't recommend returning the `Result` class in your API because it serializes it to JSON. In that process it ends up calling the `get` of the `Value` property which throws an exception when you have a failure.

**Comment by MohamedRDwedar** [comment]
@leblancdavid   i was trying to wrap the api response with the result object.
for now i will us another object in the api return hopefully that will fix soon

**Comment by vkhorikov** [comment]
As @leblancdavid said, you shouldn't return the Result from your controllers, it's not supposed to be part of your application's data contracts. Wrap it with a separate envelope class; for an example, see:
https://github.com/vkhorikov/CqrsInPractice/blob/master/After/src/Api/Controllers/StudentController.cs#L43
https://github.com/vkhorikov/CqrsInPractice/blob/master/After/src/Api/Controllers/BaseController.cs
